name: fun_n_food_vendor

description: "A new Flutter project."

publish_to: 'none'

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.19.0

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_messaging: ^14.7.10

  # UI and Widgets
  responsive_sizer: ^3.3.1
  font_awesome_flutter: ^10.7.0
  pie_chart: ^5.4.0
  score_progress_pretty_display: ^1.0.5
  simple_progress_indicators: ^0.2.0
  fluttertoast: ^8.2.5

  # HTTP
  http: ^1.2.2

  # CLI Tools
  get_cli: ^1.8.1

  # Miscellaneous
  change_app_package_name: ^1.3.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/images/