// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuOEtGWHHuhK2Yma7iCtLqa5VMBMF3Fv8',
    appId: '1:157711237253:web:5364710b3e0ede69f9a9ec',
    messagingSenderId: '157711237253',
    projectId: 'hotelmanagementvendor',
    authDomain: 'hotelmanagementvendor.firebaseapp.com',
    storageBucket: 'hotelmanagementvendor.appspot.com',
    measurementId: 'G-1RT1EPB6HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpWO2yHUfGHzZqey4JK1i3nlpO2umJmd8',
    appId: '1:157711237253:android:d5a06de3905af6a8f9a9ec',
    messagingSenderId: '157711237253',
    projectId: 'hotelmanagementvendor',
    storageBucket: 'hotelmanagementvendor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVc9b2yd6IGKYWQtoIykZ13JBm2xegOeo',
    appId: '1:157711237253:ios:45f962a31ce78673f9a9ec',
    messagingSenderId: '157711237253',
    projectId: 'hotelmanagementvendor',
    storageBucket: 'hotelmanagementvendor.appspot.com',
    iosBundleId: 'com.techpanda.vendor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVc9b2yd6IGKYWQtoIykZ13JBm2xegOeo',
    appId: '1:157711237253:ios:467902a0832d5915f9a9ec',
    messagingSenderId: '157711237253',
    projectId: 'hotelmanagementvendor',
    storageBucket: 'hotelmanagementvendor.appspot.com',
    iosBundleId: 'com.funnfood.funNFoodVendor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuOEtGWHHuhK2Yma7iCtLqa5VMBMF3Fv8',
    appId: '1:157711237253:web:1a38d96614d9efccf9a9ec',
    messagingSenderId: '157711237253',
    projectId: 'hotelmanagementvendor',
    authDomain: 'hotelmanagementvendor.firebaseapp.com',
    storageBucket: 'hotelmanagementvendor.appspot.com',
    measurementId: 'G-9QC75EE3TZ',
  );
}
